### ISSUE TITLE
composer package missing

### ISSUE THREAD

**Issue by saschagysel** [InterNACHI/blade-alpine-instantsearch#1]
Hello, I am really interested in using this for my TALL app. Could you please publish a composer package? Thanks a lot for creating and maintaining this.

**Comment by saschagysel** [comment]
I just found it here: https://packagist.org/packages/internachi/blade-alpine-instantsearch

**Comment by inxilpro** [comment]
Cool. Let me know how it works out for you. I just did a pretty big refactor to support Alpine 3, but I'm not 100% sure how this will interface with Livewire.
