### ISSUE TITLE
Implementation of Clear Refinements

### ISSUE THREAD

**Issue by martin-ro** [InterNACHI/blade-alpine-instantsearch#4]
I tried to implement the UI for `clear-refinements.blade.php` which seems to work somewhat.

```blade
<?php /** @var \Illuminate\View\ComponentAttributeBag $attributes */ ?>

<div {{ $attributes }}>
    <button type="reset" @click.prevent="refine" :disabled="!canRefine">
        {{ $slot }}
    </button>
</div>

{{-- includedAttributes (?array) --}}
{{-- excludedAttributes (?array) --}}
{{-- id (?string) --}}
```

The correct refinement list is cleared however the checkboxes stay checked. Any idea what that could be?

Great work with the package btw.!!

![demo](https://user-images.githubusercontent.com/10107779/163665853-8ae8085c-f8ae-4c3a-bcb4-ac0061584a08.gif)

**Comment by inxilpro** [comment]
From this screenshot it looks like it's clearing them but not updating the refinements list. Is that what's happening?

**Comment by martin-ro** [comment]
yes, exactly. I had the same issue with the `current-refinements` too. when I tried to implement the UI
