### ISSUE TITLE
State of the package

### ISSUE THREAD

**Issue by christophrumpel** [InterNACHI/blade-alpine-instantsearch#7]
Hey,

just came across this package, and it sounds pretty interesting. I wanted to ask what the current state of this project is. Does it work already, and do you plan to keep working on it?

Greets
Christoph

**Comment by inxilpro** [comment]
It does work, and we're using it (in a fairly limited way) in production, so we definitely plan on continuing to support it. It doesn't get a ton of attention, if I'm honest, but it kinda "just works" so there's not a ton of upkeep.

**Comment by inxilpro** [comment]
Here's a quick sample of working code, since there's not much in the way of docs right now…

```blade
<x-instantsearch
  :application-id="$algolia_config['app_id']"
  :search-key="$algolia_config['key']"
  :index-name="$algolia_config['index']"
  routing
>

<x-instantsearch::search-box
  autofocus
  placeholder="Search people…"
  class="block p-2 w-full text-base leading-normal text-gray-700 bg-white rounded-sm border focus:ring"
/>


<x-instantsearch::hits>

  <div>
    <h1><x-instantsearch::highlight attribute="name" /></h1>
    <x-instantsearch::snippet attribute="about_me" tag-name="div" />
  </div>

</x-instantsearch::hits>

<x-instantsearch::pagination class="my-8" />

</x-instantsearch>
```

**Comment by christophrumpel** [comment]
Nice thanks @inxilpro and good to hear. Will give it a try 👍
